"""Master Orchestrator FastAPI application.

Provides a unified interface for Chaos Planning and Execution.
"""

from __future__ import annotations

import sys
import os

# Add the app directory to the path
sys.path.insert(0, os.path.dirname(__file__))

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from langchain_core.messages import HumanMessage

from graph.master import build_master_graph
from config import settings

# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Chaos Master Orchestrator",
    description="Unified LangGraph agent for Chaos Engineering (Planning + Execution).",
    version="3.0.0",
)

# Single unified graph instance
_master = build_master_graph()


# ── Schemas ───────────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    thread_id: str
    message: str


# ── Helpers ───────────────────────────────────────────────────────────────────

def _config(thread_id: str) -> dict:
    return {"configurable": {"thread_id": thread_id}}


def _last_ai_message(state_values: dict) -> str:
    """Extract the latest non-tool-call AI message text."""
    from langchain_core.messages import AIMessage
    for msg in reversed(state_values.get("messages", [])):
        if isinstance(msg, AIMessage) and not getattr(msg, "tool_calls", None):
            content = msg.content
            if isinstance(content, list):
                content = " ".join([c.get("text", "") for c in content if isinstance(c, dict) and "text" in c])
            if content:
                return str(content)
            else:
                return "*No text output generated by the AI (empty response).*"
    return ""


# ── Routes ────────────────────────────────────────────────────────────────────

@app.post("/chat")
async def chat(request: ChatRequest):
    """Unified endpoint for the entire Chaos Lifecycle."""
    config = _config(request.thread_id)

    try:
        current = _master.get_state(config)
        paused = len(current.next) > 0

        if paused:
            # Resume from human_feedback interrupt
            _master.update_state(config, {"messages": [HumanMessage(content=request.message)]})
            gen = _master.stream(None, config, stream_mode="values")
        else:
            # Brand-new turn
            inputs = {"messages": [HumanMessage(content=request.message)]}
            gen = _master.stream(inputs, config, stream_mode="values")

        last_values = None
        for state_values in gen:
            last_values = state_values

        latest = _master.get_state(config)
        waiting = len(latest.next) > 0
        
        state_to_check = last_values or latest.values or {}
        active_nodes = list(latest.next)
        
        # If the graph is waiting for human feedback, the next agent will always be the supervisor
        if "human_feedback" in active_nodes:
            current_agent = "supervisor"
        else:
            current_agent = state_to_check.get("next_agent", "supervisor")
        
        return {
            "thread_id": request.thread_id,
            "status": "waiting_for_user" if waiting else "completed",
            "message": _last_ai_message(state_to_check),
            "active_agent": current_agent,
            "pending_nodes": active_nodes,
        }

    except Exception as exc:
        print("=================================")
        print('Error in Chaos Orchestrator: ', exc)
        print("=================================")
        raise HTTPException(status_code=500, detail=str(exc))


# ── State Management ──────────────────────────────────────────────────────────

@app.get("/state/{thread_id}")
async def get_state(thread_id: str):
    """Inspect the current state of a thread."""
    config = _config(thread_id)
    state = _master.get_state(config)

    if not state.values:
        return {"thread_id": thread_id, "status": "not_found", "state": None}

    return {
        "thread_id": thread_id,
        "status": "waiting_for_user" if len(state.next) > 0 else "completed",
        "pending_nodes": list(state.next),
        "active_agent": state.values.get("next_agent", "supervisor"),
        "message_count": len(state.values.get("messages", [])),
    }


@app.delete("/state/{thread_id}")
async def reset_state(thread_id: str):
    """Reset / clear a conversation thread."""
    config = _config(thread_id)
    try:
        _master.update_state(config, {"messages": [], "confirmed": False, "completed": False})
    except Exception:
        pass
    return {"thread_id": thread_id, "status": "reset"}


@app.get("/health")
async def health():
    return {"status": "ok", "llm_provider": settings.llm_provider, "orchestrator": "v3-master"}
