apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chaos-ns
  labels:
    app: chaos-frontend
spec:
  selector:
    app: chaos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
