apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: chaos-ns
  labels:
    app: chaos-agent
spec:
  selector:
    app: chaos-agent
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
