"""Shared helper utilities for API route handlers."""

from __future__ import annotations


def config(thread_id: str) -> dict:
    """Build a LangGraph runnable config for the given thread."""
    return {"configurable": {"thread_id": thread_id}}


def last_ai_message(state_values: dict) -> str:
    """Extract the latest non-tool-call AI message text from state."""
    from langchain_core.messages import AIMessage

    for msg in reversed(state_values.get("messages", [])):
        if isinstance(msg, AIMessage) and not getattr(msg, "tool_calls", None):
            content = msg.content
            if isinstance(content, list):
                content = " ".join(
                    c.get("text", "")
                    for c in content
                    if isinstance(c, dict) and "text" in c
                )
            if content:
                return str(content)
            return "*No text output generated by the AI (empty response).*"
    return ""
